### ISSUE TITLE
English mistakes

### ISSUE THREAD

**Issue by chaficnajjar** [getbem/getbem.com#116]
I think the following sentence:

"_Some of them are less strict and more flexible, other is easier to understand and adapt in team._"

should be:

"_Some of them are less strict and more flexible, **others are** easier to understand and adapt in **a** team._"

**Comment by floatdrop** [comment]
@chaficnajjar yep. Want to make a PR?

**Comment by floatdrop** [comment]
@chaficnajjar thanks!
