### ISSUE TITLE
Small English Fixes in the Heading of The Naming Section

### ISSUE THREAD

**Issue by code-warrior** [getbem/getbem.com#117]
Consider changing…

It is known fact, that the right styleguide can significantly increase development speed, debugging and implementing new features in legacy code. Sadly, most CSS codebase is developed without (sometimes) any structure and naming conventions. This leads to an unmaintainable CSS codebase in the long term.

To…

It is **a** known fact that the right styleguide can significantly increase development speed, debugging**,** and **the implementation of** new features in legacy code. Sadly, most CSS codebase**s** **are sometimes** developed without any structure **or** naming conventions. This leads to an unmaintainable CSS codebase in the long term.

**Comment by floatdrop** [comment]
Fixed with https://github.com/getbem/getbem.com/pull/118 Thanks!
