### ISSUE TITLE
Inconsistency with bem.info - Single dash vs. double dash

### ISSUE THREAD

**Issue by Malax** [getbem/getbem.com#119]
Hi!

While digging for more info about BEM, we found that getbem.com and bem.info contradict each other regarding naming of modifiers.

> The modifier name is separated from the block or element name by a single underscore (_).
https://en.bem.info/methodology/quick-start/#modifier

getbem and basically every other resource I found on the internet uses two underscores. bem.info lists this style as _Two Dashes style_. In a discussion with team members, the question "Why are we using an alternative style?" arose.

Can someone shed some light onto this? Is bem.info just outdated on that regard?

**Comment by tadatuta** [comment]
@Malax bem.info is not outdated but uses convention which was invented at the very beginning and is just fine. `Two Dashes style` was introduced later but has no any distinct advantages. It's just a matter of taste.

See https://en.bem.info/methodology/naming-convention/#which-style-to-choose

**Comment by tadatuta** [comment]
BTW, take a look at https://github.com/rebem/css

**Comment by Malax** [comment]
Thanks for your answer! I guess it's a bit my fault considering BEM also a style guide for CSS. It's more a methodology than a style guide I guess. Anyway, this means you cannot say: "_We're doing BEM_" but need to add what kind of style you use.

This might be a good Idea to state that on getbem.com so other will not run into the same issue. getbem.com is consistent regarding the style, but if you dig deeper you find others and might get into the confused state.

Anyway, this Issue can be closed - but maybe you guys can take the idea into consideration. :)
