### ISSUE TITLE
Add .idea to .gitignore

### ISSUE THREAD

**Issue by code-warrior** [getbem/getbem.com#122]
It would be a good idea to add JetBrains’ `.idea` folder to `.gitignore`.

**Comment by iamstarkov** [comment]
sorry, can you explain more?

**Comment by code-warrior** [comment]
By all means.

WebStorm, made by the folks at JetBrains, generates a cache folder called `.idea` at the root of every project. If `.idea` is not listed in `.gitignore`, then I have to remember to keep excluding it when working on this project, because Git sees the folder as an untracked folder.

Adding `.idea` to `.gitignore` will make it easier for WebStorm users to not forget to exclude the folder when working on this project.

**Comment by iamstarkov** [comment]
got it, feel free to add it in next pr
