### ISSUE TITLE
Is there more to BEM than naming blocks, elements and modifiers? 

### ISSUE THREAD

**Issue by StefanTosic23** [getbem/getbem.com#134]

**Comment by tadatuta** [comment]
Sure! See https://en.bem.info/

**Comment by floatdrop** [comment]
@StefanTosic23 it depends on what you searching for. For examples this approach can be generalized to structure your project folders and even structure dependencies (see [bemjson](https://en.bem.info/platform/bemjson/)) – but (imo) CommonJS is more simple and understandable approach.
