### ISSUE TITLE
Does BEM make sense in combination with angular?

### ISSUE THREAD

**Issue by enyo** [getbem/getbem.com#138]
Since angular encapsulates CSS directives so they don't bleed into other components, does that not provide the same benefit as using BEM?

If not, what are good examples of angular apps that use BEM

**Comment by iamstarkov** [comment]
CSS methodologies doesnt interfere with JS frameworks. That said, its not JS frameworks' responsibility to write maintanable css code, so yeah BEM makes sense with angular

**Comment by enyo** [comment]
Well it's not a simple JS framework, but it completely rewrites CSS code to provide (css scoping)[https://drafts.csswg.org/css-scoping/] which directly affects the CSS written. Hence my question.

**Comment by iamstarkov** [comment]
@enyo if framework handles selectors' scopes for you, then you might not need BEM that much
