### ISSUE TITLE
Dead link to "Maintainable CSS with BEM"

### ISSUE THREAD

**Issue by Kwadz** [getbem/getbem.com#146]
The screenshot:  

<img width="477" alt="screen shot 2017-09-04 at 21 21 57" src="https://user-images.githubusercontent.com/1472599/30036914-71df3380-91b7-11e7-8699-09ad3452ebe2.png">

**Comment by KulaGGin** [comment]
@Kwadz Yes, but you could've fixed it yourself. Here:
https://web.archive.org/web/20170723121937/http://www.integralist.co.uk/posts/bem.html

**Comment by Kwadz** [comment]
@KulaGGin You're welcome.

**Comment by Integralist** [comment]
https://github.com/Integralist/integralist.github.com/issues/5#issuecomment-546883645

**Comment by Kwadz** [comment]
Thanks @Integralist!
