### ISSUE TITLE
Show the list of contributors to the pages

### ISSUE THREAD

**Issue by varya** [getbem/getbem.com#42]
Info can be taken from git history. Looks like bem.info does similar thing.

**Comment by matmuchrapna** [comment]
link to https://github.com/getbem/getbem.com/graphs/contributors is not acceptable anymore?

**Comment by varya** [comment]
This link is buried too deep. I think that having the authors and contributors names right on the page would encourage people to contribute. We don't need a page about every person, just a list of names below each article.

**Comment by floatdrop** [comment]
Looks like it would take modification in building (downloading list of contributors) - which will give unnecessary complexity to building or dynamic download contributors from http://github.com/getbem/getbem.com/graphs/contributors

Maybe it is better to depersonalize content on getbem.com (if @ingdir is not against it on http://getbem.com/naming/).

What do you think?

**Comment by matmuchrapna** [comment]
I'm agreed with @floatdrop

**Comment by matmuchrapna** [comment]
also we have "Fork me on github" label and "Edit / Improve" button on each page

**Comment by matmuchrapna** [comment]
@ingdir what do you think about content depersonalisation?

**Comment by ingdir** [comment]
I'm 100% okay with that
