### ISSUE TITLE
Add how-to rebase/move images while building CSS to docs

### ISSUE THREAD

**Issue by dab** [getbem/getbem.com#51]
If I building the project from BEM-like filestructure — all images are in their block's folders. I think it is another block technology. So I should move images to some `./assets/images/` folder and rebase url's in CSS.

How do you manage your image files? 

I think it can be good to have a note about this issue in build docs. Thanks.

**Comment by iamstarkov** [comment]
>  think it is another block technology

what do you mean by "block technology"?

**Comment by dab** [comment]
@iamstarkov for instance `CSS` and `JavaScript` — another block techs.

**Comment by floatdrop** [comment]
@dab it depends wholly on how you transfer your images to destanation folder. In most common case you will need to use something like https://www.npmjs.com/package/gulp-css-url-adjuster/

**Comment by iamstarkov** [comment]
I don’t want to rely on "tech" term because it’s vendored by yandex, and very restricted to build flow. Also it is not tech, it is simple files. And it’s all up to you, how to store you code and how to build it. General modularization rule to separate code into small pieces is working great for bem.

**Comment by iamstarkov** [comment]
@dab Also, @floatdrop is right, you can use one of the tons of npm modules to deal with rebasing urls in the file sources

**Comment by iamstarkov** [comment]
@SilentImp subscribe test

**Comment by dab** [comment]
@iamstarkov @floatdrop The question was about your recommended practices. Maybe you using some magic tool for this task :fireworks: 
Thanks.

**Comment by iamstarkov** [comment]
@dab I used to use `gulp.src('blocks/**').pipe(gulp.dest('dist/blocks'));` and was fine with that. I implemented it in test assignment for csssr, you can check and play it here https://github.com/iamstarkov/csssr-profile
