### ISSUE TITLE
Can I use element of block #1 inside block #2 which in turn is inside in block#1?

### ISSUE THREAD

**Issue by schnaider** [getbem/getbem.com#54]
For instance:
...
<div class="post__header">
    <div class="user-card">
        <div class="user-card__userpic">
            <img class="userpic userpic_type_round".../>
        </div>
        <div class="user-card__text">
            <span class="user-card__username">User Name</span>

            
            <span class="post__meta">2 hours ago</span>

        </div>
    </div>
</div>

**Comment by iamstarkov** [comment]
Sorry, I didn’t get you question. Can you describe it in more details?

**Comment by floatdrop** [comment]
> Parts of a block and have no standalone meaning. They are semantically tied to its block.

@schnaider it is up to how you interpret `standalone` - because `post__meta` in fact is child of `post__header` - so nothing wrong here. But I suggest to avoid use CSS rules, that depends on other elements of other blocks (like this `.user-card__text .post__meta`).

**Comment by Guria** [comment]
:+1: for @floatdrop 
* placement in html is definitely ok
* using in css highly recommended to avoid

BTW, there is also [forum on bem.info](https://en.bem.info/forum).
