### ISSUE TITLE
Block modifiers that effect elements

### ISSUE THREAD

**Issue by SevereOverfl0w** [getbem/getbem.com#68]
I'm not sure if & where this falls into the BEM methodology, but I'm interested in where this might fall.

If I have a block modifier, for example "xmas," and I want the elements within that block to also be xmas themed, how would it be best to do it.

Does a `--xmas` suffix for every element seem necessary? Or would this be the one use-case for nesting (e.g. `block--xmas block__elem { ... }`?

**Comment by tadatuta** [comment]
@SevereOverfl0w Second assumption is right: https://en.bem.info/faq/#why-should-i-avoid-using-nested-selectors

**Comment by SevereOverfl0w** [comment]
Ah, I didn't know there was *another* bem site, thanks!

**Comment by varya** [comment]
Hey @SevereOverfl0w! We developed more detailed answer and published it on the website http://getbem.com/faq/#block-modifier-affects-elements
Thanks for the question :-)
