### ISSUE TITLE
naming element used in many blocks

### ISSUE THREAD

**Issue by moonsin** [getbem/getbem.com#72]
I want to know. if there is an element that many blocks have used it.these blocks are block1,block2,block3... Then ,How should I name this element?

**Comment by floatdrop** [comment]
If this element is used in many other blocks – then this is a block. Elements (by definition) can not be used outside of it's block.

**Comment by iamstarkov** [comment]
@floatdrop is right

**Comment by moonsin** [comment]
@floatdrop thank u very very much!
