### ISSUE TITLE
`.block__mod--mod` wrong?

### ISSUE THREAD

**Issue by fdeberle** [getbem/getbem.com#77]
The section „Modifier“ on http://getbem.com/naming/ contains the example `.block__mod--mod` in the explanation text.

See https://github.com/getbem/getbem.com/blob/d23fbcac1f5e976cbd415cd7737f6d1fd2d0f2c9/src/naming.jsx#L102

Shouldn't it be `.block__elem--mod`?

**Comment by floatdrop** [comment]
@fdeberle yeah, this is a typo. Thanks 🌴
