### ISSUE TITLE
Block modifier affecting sub-block elements

### ISSUE THREAD

**Issue by ncoden** [getbem/getbem.com#85]
Hi.

I have a quite complicated and very specific situation. I found a "fix" but I don't like it. So I will explain it step by step to the "fix" I found. I hope you will be able to purpose to me something better :)

I have the following CSS and HTML:
```scss
.my-block.myblock--modifier .myblock__element { ... }
```
```scss
my-block my-block--modifier
  my-block__element /* affected */
    my-block
      my-block__element /* affected but unexpected */
```
With the `--modifier` which should affect `__element`. The problem is that **the sub-block element is affected too by the `--modifier`**.

Two solutions:
**1**. ~~Direct nesting `block` and `element`~~ *Beurk, dirty*
```css
.my-block.myblock--modifier > .myblock__element { ... }
```
**2**. Add modifier class on element
```scss
.myblock--modifier { ... }
.myblock--modifier__element { ... }
```
```scss
my-block my-block--modifier
  my-block__element my-block--modifier__element
    my-block
      my-block__element /* not affected */
```

But.
**2.1**. **Can we consider than a block *encapsulates* its elements ?** If yes, we shouldn't care that the block `--modifier` is affecting `__element`. A solution can be to always apply modifier on elements too, regardless if its modifier is affecting it or not. It's hard to write but maybe it can be automated on JS frameworks.

**2.2**. I'm working on a semantic SCSS, with something like this:
```scss
@mixin my-block--modifier {
  /* will generate .header__my-block .my-block__element */
  .my-block__element { ... }
}

...

.header {
  /* this header element is called as the block because we assume it is this block */
  &__my-block {
    /* modifier applied with @include so it can be applied for a particular breakpoint */
    @include my-block--modifier;
  }
}
```
```scss
header
  header__my-block my-block
    my-block__element
      my-block
        my-block__element /* affected */
```

To resolve this situation as I done at **2**, I can do :
```scss
@mixin my-block--modifier {
  /* will generate .header__my-block__element */
  &__element { ... }
}
...

```
```scss
header
  header__my-block my-block
    header__my-block__element my-block__element
      my-block
        my-block__element /* not affected */
```

But **it create a lot of long classes to apply**, with the same **2.1** problem. *`header__my-block__...` will have to be applied on each element.

Can you advise me better practices ? I tried to numerate my questions and problems so you can give step-by-step responses :)

*I'm working on https://github.com/ncoden/caliopen.web-client-ng/tree/refactor/foundation . Take a look if you want to see what give a semantic SCSS on a medium-big project*

**Comment by ncoden** [comment]
(poke @iamstarkov @varya)

**Comment by f0rmat1k** [comment]
@ncoden I think, you shouldn't use `myblock` inside of `myblock`. IMHO it's kind of anti-pattern of BEM.

**Comment by ncoden** [comment]
@f0rmat1k It's a DOM representation. If a BEM component can recommend a "standard use", BEM allows to use and nest your blocks as you want, reorder its elements or put them lower in the DOM tree...

**Comment by f0rmat1k** [comment]
@ncoden yes, it's allows, but in my opinion it's something like an anti-pattern.

**Comment by ncoden** [comment]
Let's clarify what is anti-pattern, so what pattern you should follow where.

- BEM is a syntax for an OO approach : the pattern is to define consistent and modular objects, *elements inside block. modifier modify block*
- DOM is an empty room where you freely place and nest your objects : the pattern is *Do what the fuck you want here*
- So BEM in DOM is *Do what the fuck you want, as long as you apply a block modifier on this block, and you keep a block element inside this block*.

**Comment by f0rmat1k** [comment]
You are right, but as i know, important goal of BEM — isolation of block styles and solving css global namespace. When you are using "myblock myblock--modifier" > "myblock" you're losing independence of nested "myblock" (reason why you came here). It's just my opinion. I haven't needed to inser block into the same in 2 years of using BEM.
We can also ask for @tadatuta what he thinks about described situation.

**Comment by f0rmat1k** [comment]
btw anti-pattern ≠ prohibited.
For example, this is anti-pattern but legal BEM code:
`<div class="some-block some-block-1"></div>`.
Better to use `<div class="some-block some-block_num_1"></div>`.

**Comment by ncoden** [comment]
No. "myblock" is still fully independant.

I want to be able to **use** "myblock" as :
```
myblock myblock--modifier
  myblock
    ...
```

But I will **never declare** "myblock" rules like:
```scss
.myblock > .myblock { ... }
```

If having a "block" inside an other modified "block" create side effects (deeper block elements are affected too by modifier), it actually make the "block" component not independent. Because you're not able to use it in any situation.

**Comment by iamstarkov** [comment]
@ncoden 
> But I will never declare "myblock" rules like:

this. its fine, while you are working alone. Once you are creating components within a team, there is no guarantee this wont happen

**Comment by ncoden** [comment]
@iamstarkov :+1: I should say:
> But we **shouldn't declare** "myblock" rules like:

*Because IT is anti-pattern.*

**Comment by f0rmat1k** [comment]
@ncoden btw i mean not `.class > .class` but nesting of the same blocks.
```
myblock myblock--modifier
   myblock
       myblock__elem
```
leads to losing independency of nested `myblock__elem`, because another block affects on it (even if it's the same block).
The second point: which of the two myblock is a truly parent of `myblock__elem`? No answer, we don't know exactly. It's a reason, why i think, that it's anti-pattern.

**Comment by ncoden** [comment]
> leads to losing independency of nested myblock__elem, because another block affects on it

It's the purpose of this issue.
```scss
        myblock__elem myblock--modifier__elem
```
instead of
```scss
        myblock__elem
```

> which of the two myblock is a truly parent-block of myblock__elem? No answer, we don't know exactly

It is the child of the closer same parent. For exemple:
```scss
myblock     // (1)
    myblock // (2)
        myblock__elem // child of (2) at its recommended place
```

```scss
myblock myblock--blue     // (1)
    myblock // (2)
        myblock__elem myblock--blue__elem // child of (1) placed inside (2)
```

**Comment by f0rmat1k** [comment]
@ncoden So I advise you to just use the `>` in css.

**Comment by ncoden** [comment]
@f0rmat1k The *common* case, not the *only* case.

The following situation is proper and possible
```scss
mylist mylist--vertical
    u-padding // or what you want
        mylist__item mylist--vertical__item
        mylist__item mylist--vertical__item
            mycomponent
                mylist
                    an-another-random-component
                        mylist__item
```

**Comment by f0rmat1k** [comment]
@ncoden Ye, now i see. It looks like real methodology problem. I think there isn't common solution, you should process such situation differently. E.g. you can remove the cascade by using elemMods instead of mods of block.

**Comment by ncoden** [comment]
@f0rmat1k I'll use `block__element--modifer` when a modifier can be freely applied on one element, independently of the other. Here, the modifier is semantically attached to the `block`, so I prefer to use `block--modifier__element` to clearly indicate *You __should__ apply this modifier on all elements too*.

Thank you a lot @f0rmat1k and @iamstarkov for your help. I didn't found a better solution, but you helped me to organize my point of view.

I will come back to you if I found a better way :)
