### ISSUE TITLE
Typos in "global CSS resets" FAQ example snippet

### ISSUE THREAD

**Issue by adi518** [getbem/getbem.com#96]
Example snippet says:

`.menu {
    @include reset-list;
}
.menu__item {
    @include reset-list-item;
}`

Shouldn't that be `reset-menu` and `reset-menu-item`?

http://getbem.com/faq/#global-css-resets

**Comment by floatdrop** [comment]
No. These are resets for lists and menu is assumed to be a list. So:

> to prevent copy-paste

In example we include same resets.
