### ISSUE TITLE
How do I know what a block should be?

### ISSUE THREAD

**Issue by pauldoerwald** [getbem/getbem.com#97]
In the Github example mockup you show that each of the 3 large input fields is a block. However, couldn't it be said that the form is a block and the input field therein are elements? How would BEM prevent one developer/designer from creating inputs-as-blocks and another developer/designer creating form-as-block-and-inputs-as-elements, or encourage them in the right way?

**Comment by floatdrop** [comment]
If `form` as one element suits your needs – you can make `form` a block, but it is highly recommended to split your code in more reusable components. For example button can be used without form (for navigation for example).

For more examples of blocks, you can look at [bem-components](https://github.com/bem/bem-components) – this library is close to what Yandex use for projects.
